site_name: My site
site_url: https://duniang818.git.io/superset-fork/
repo_url: https://github.com/duniang818/superset-fork
repo_name: superset-fork
edit_uri: edit/master/docs/

theme:
  name: material
  features:
    - navigation.top
    - navigation.tabs
    - navigation.sections
    - navigation.path
    - navigation.indexes



nav:
  - 首页: index.md
  - 工具: tools/tools-index.md
  - 分析: analysis/analysis-index.md
  - 汽车: car/car-index.md
  - 生活: life/life-index.md
  - 博客: blog/blog-index.md
  - GitFork: gitfork/gitfork-index.md
  - Todo: todos/todos-index.md


plugins:
  - search
  - blog:
     blog_dir: blog/posts